"""welcome_leave_channel_to_string

Revision ID: 07c05549ae00
Revises: 24933d669517
Create Date: 2022-04-20 16:01:08.452443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "07c05549ae00"
down_revision = "24933d669517"
branch_labels = None
depends_on = None


def upgrade():
    op.alter_column("guilds", "welcome_channel", type_=sa.String)
    op.alter_column("guilds", "leave_channel", type_=sa.String)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
