"""Added Playlist and PlaylistSong models

Revision ID: 1b6128ae5a4b
Revises: 228333096592
Create Date: 2022-11-13 20:47:10.607861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1b6128ae5a4b"
down_revision = "228333096592"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlists",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "playlist_songs",
        sa.Column("uri", sa.String(), nullable=False),
        sa.Column("playlist_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["playlist_id"], ["playlists.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("uri"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("playlist_songs")
    op.drop_table("playlists")
    # ### end Alembic commands ###
