"""imp_log_table

Revision ID: 228333096592
Revises: 07c05549ae00
Create Date: 2022-04-21 11:50:59.700208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "228333096592"
down_revision = "07c05549ae00"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "impersonation_logs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("impersonator_id", sa.BigInteger(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("impersonation_logs")
    # ### end Alembic commands ###
