"""add guild_id to auto resp

Revision ID: c534a7e185b6
Revises: 0a13ce529f35
Create Date: 2022-04-05 18:39:59.392001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c534a7e185b6"
down_revision = "0a13ce529f35"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auto_responses",
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auto_responses", "guild_id")
    # ### end Alembic commands ###
